Repository FrancisTR/GameJam-FallDown, pull requests merged in 2024-08, with the labels that each got.

#5 Add empty Unity project and .gitignore file
  .gitignore
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/AudioManager.asset
  ProjectSettings/ClusterInputManager.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/MemorySettings.asset
  ProjectSettings/NavMeshAreas.asset
  ProjectSettings/NetworkManager.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/QualitySettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
  ProjectSettings/TimeManager.asset
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/VFXManager.asset
  ProjectSettings/VersionControlSettings.asset
  ProjectSettings/XRSettings.asset
Labels: enhancement

#7 Update README.md
  README.md
Labels: documentation

#8 added name to team member list
  README.md
Labels: documentation

#9 Improve main menu (quit, scene)
  Assets/Scenes/Main_Menu.unity
  Assets/Scenes/Main_Menu.unity.meta
  Assets/Scenes/PlayScene.unity
  Assets/Scenes/PlayScene.unity.meta
  Assets/Scenes/QuitGame.cs
  Assets/Scenes/QuitGame.cs.meta
  Assets/Scenes/TempBackground.jpg
  Assets/Scenes/TempBackground.jpg.meta
  ProjectSettings/BurstAotSettings_StandaloneLinux64.json
  ProjectSettings/BurstAotSettings_WebGL.json
  ProjectSettings/CommonBurstAotSettings.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TimelineSettings.asset
Labels: enhancement

#13 Add Character Movement
  Assets/Scenes/PlayScene.unity
  Assets/Scenes/PlayerMovement.cs
  Assets/Scenes/PlayerMovement.cs.meta
  Assets/Scenes/TempPlayer.jpg
  Assets/Scenes/TempPlayer.jpg.meta
  README.md
Labels: documentation, enhancement

#21 Finish level 1
  Assets/Scenes/Level1.unity
Labels: enhancement

#22 Fix Level1 invisible collision at bottom floor
  Assets/Scenes/Level1.unity
Labels: enhancement

#25 Simple Scene Transitions
  Assets/Scenes/Main_Menu.unity
  Assets/Scenes/SceneTransition.cs
  Assets/Scenes/SceneTransition.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#26 Removed and readded Level1 scene since it was broken
  Assets/Scenes/Level1.unity
  Assets/Scenes/Level1.unity.meta
Labels: enhancement
